config/routes.rb
Fanbase::Application.routes.draw do
  
  

  resources :users
  resources :sessions, :only => [:new, :create, :destroy] # the ":only" and hash restricts the full set of CRUD to just those listed

  resources :sports do
    resources :teams
  end
  
  resources :sports do
    resources :types
  end
  
  resources :types do
    resources :events
  end
  

  resources :teams do
    resources :players
  end
  
  resources :teams do
    resources :contests
  end
      
  resources :contests do
    resources :branches
  end
  

  
  
  resources :users do
    resources :branches
  end
  

  
  root :to => 'pages#home'
  
  get "sessions/new"
  get "pages/home"
  
  match '/admin', :to => 'pages#admin'
  match '/signup', :to => 'users#new' 
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match 'contest/:team_id/team/:team_id/players', :to => 'team#players#index'

  

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  
  attr_accessible :description, :season# ,  :team_attributes
  has_many :teams, :dependent => :destroy
  has_many :types, :dependent => :destroy
  
  # accepts_nested_attributes is necessary, I don't really know why
  accepts_nested_attributes_for :teams
  accepts_nested_attributes_for :types
  
  
  # validates :description, :presence => true
  # 
  # validates :season, :presence => true
  
  validates_each  :description,
                  :season,
                  do |record, attr, value|
                    if value.blank?
                      record.errors.add(attr, "can't be blank.")
                    end
                  end 
  end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  
  before_filter :authenticate
  before_filter :authenticate_admin
  
  
  
  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sports }
    end
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
    @sport = Sport.find(params[:id])
    # @team = Team.new(:sport => @sport)
 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sport }
    end
  end

  # GET /sports/new
  # GET /sports/new.json
  def new
    @sport = Sport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sport }
    end
  end

  # GET /sports/1/edit
  def edit
    @sport = Sport.find(params[:id])
  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(params[:sport])

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render json: @sport, status: :created, location: @sport }
      else
        format.html { render action: "new" }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sports/1
  # PUT /sports/1.json
  def update
    @sport = Sport.find(params[:id])

    respond_to do |format|
      if @sport.update_attributes(params[:sport])
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport = Sport.find(params[:id])
    @sport.destroy

    respond_to do |format|
      format.html { redirect_to sports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_for(@sport) do |f| %>
  <% if @sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% @sport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :season %><br />
    <%= f.text_field :season %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<h1>Listing sports</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Season</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sports.each do |sport| %>
  <tr>
    <td><%= sport.description %></td>
    <td><%= sport.season %></td>
    <td><%= link_to 'Show', sport %></td>
    <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
    <td><%= link_to 'Types', sport_types_path(sport) %></td>
    <td><%= link_to 'Teams', sport_teams_path(sport) %></td>
    <td><%= link_to 'Destroy', sport, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New sport</h1>

<%= render 'form' %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @sport.description %>
</p>

<p>
  <b>season:</b>
  <%= @sport.season %>
</p>


<%= link_to 'New Team', new_sport_team_path(@sport)%> |
<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>