config/routes.rb
Fanbase::Application.routes.draw do
  
  

  resources :users
  resources :sessions, :only => [:new, :create, :destroy] # the ":only" and hash restricts the full set of CRUD to just those listed

  resources :sports do
    resources :teams
  end
  
  resources :sports do
    resources :types
  end
  
  resources :types do
    resources :events
  end
  

  resources :teams do
    resources :players
  end
  
  resources :teams do
    resources :contests
  end
      
  resources :contests do
    resources :branches
  end
  

  
  
  resources :users do
    resources :branches
  end
  

  
  root :to => 'pages#home'
  
  get "sessions/new"
  get "pages/home"
  
  match '/admin', :to => 'pages#admin'
  match '/signup', :to => 'users#new' 
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match 'contest/:team_id/team/:team_id/players', :to => 'team#players#index'

  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  
  attr_accessible :name, :first_game, :last_game, :start, :end, :id, :team_id
  # attr_accessible :team_id, :category_id
  belongs_to :team, :foreign_key => "team_id"
  
  has_many :branches
  has_many :events
  
  # belongs_to  :category, :class_name => 'Category', :foreign_key =>"category_id"
  accepts_nested_attributes_for :branches
  
  def players_count
    
  end

end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  
  before_filter :authenticate
  
  # GET /contests
  # GET /contests.json
  def index
    if !params[:team_id].nil?
      @team = Team.find(params[:team_id])
      # @team.sort_by{|t| t[:end]}
      @contests = @team.contests.sort_by{|c| c[:end]}.reverse
    else
    @contests = Contest.all.sort_by{|c| c[:end]}.reverse
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contests }
    end
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    # @team = Team.find(params[:team_id])
    @contest = Contest.find(params[:id])
    @team = @contest.team
    @categories = Category.all
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: [@contest] }
    end
  end

  # GET /contests/new
  # GET /contests/new.json
  def new
    @team = Team.find(params[:team_id])
    @contest = Contest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contest }
    end
  end

  # GET /contests/1/edit
  def edit
    @team = Team.find(params[:team_id])    
    @contest = Contest.find(params[:id])
  end

  # POST /contests
  # POST /contests.json
  def create
    @team = Team.find(params[:team_id])
    @contest = @team.contests.build(params[:contest_id])

    respond_to do |format|
      if @contest.update_attributes(params[:contest])
        format.html { redirect_to [@team, @contest], notice: 'Contest was successfully created.' }
        format.json { render json: [@contest], status: :created, location: [@contest] }
      else
        format.html { render action: "new" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contests/1
  # PUT /contests/1.json
  def update
    # @team = Team.find(params[:team_id])
    @contest = Contest.find(params[:id])
    @team = @contest.team
    if !params[:category_id].nil?
      @category = Category.find(params[:category_id]) 
      @contest.update_attributes(:category_id => @category.id)
    end

    respond_to do |format|
      if @contest.update_attributes(params[:contest])
        format.html { redirect_to [@team, @contest], notice: 'Contest was successfully updated. Yes.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @team = Team.find(params[:team_id])
    @contest = Contest.find(params[:id])
    @contest.destroy

    # @contest = Contest.find(params[:id])
    # @contest.destroy

    respond_to do |format|
      format.html { redirect_to team_contests_url }
      format.json { head :no_content }
    end
  end
  
  
  # def make_contest_category
  #   @category = Category.find(params[:category])
  #   @contest.find(params[:contest_id])
  #   @team = @contest.team
  #   # @contest.category = @category
  #   @contest.update_attributes(:category_id => @category.id)
  #   # @contest = @category.contests.build(params[:contest_id])
  #   
  #   # @contest.save!
  #   
  #   respond_to do |format|
  #      if @contest.update_attributes(params[:contest])
  #        format.html { redirect_to [@team, @contest], notice: 'makeContestCategory was successfully run.' }
  #        format.json { head :no_content }
  #      else
  #        format.html { render action: "edit" }
  #        format.json { render json: @category.errors, status: :unprocessable_entity }
  #      end
  #    end
  # end
  
  
  # def joinable_contests
  #   @contests = Contest.all
  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @contests }
  #     # render :layout => 'joinable_contests'
  #     render 'joinable_contests'
  #   end
  # end
  
  
  
end

app/helpers/contests_helper.rb
module ContestsHelper
  

  
end

app/views/contests/_form.html.erb
<%= form_for([@team, @contest]) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_game %><br />
    <%= f.number_field :first_game %>
  </div>
  <div class="field">
    <%= f.label :last_game %><br />
    <%= f.number_field :last_game %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<%= link_to 'Show', team_contest_path %> |
<%= link_to 'Back', team_contests_path %>

app/views/contests/index.html.erb
<h1>Games</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Game</th>
    <th>Entry Deadline</th>
    <th></th>
	<% if signed_in? && admin? %>
	<th>Branches</th>
    <th></th>
    <th></th>
    <th></th>
	<% end %>
  </tr>

<% @contests.each do |contest| %>
  <tr>
    <td><%= contest.name %></td>
    <td><%= contest.first_game %></td>
    <td><%= contest.end.strftime("%B %d, %Y") %></td>
	<td><%= if contest.end > DateTime.now then
			link_to 'Join', contest_branches_path(contest) else
			'Closed' end %> </td>
	<% if signed_in? && admin? %>
   	<td><%= link_to 'Branches', contest_branches_path(contest) %></td>
    <td><%= link_to 'Team', sport_team_path(contest.team.sport, contest.team) %></td>
    <td><%= link_to 'Edit', edit_team_contest_path(@team, contest) %></td>
    <td><%= link_to 'Destroy', 	team_contest_path(@team, contest), 
								confirm: 'Are you sure?', 
								method: :delete %></td>
	<% end %>
  </tr>
	<% end %>
</table>

<% if signed_in? && admin? %>
<% if !params[:team_id].nil? %>
<%= link_to 'New Contest', new_team_contest_path %>
<%end%>
<% end %>

app/views/contests/index.mobile.erb
<h3>Next games</h3>
	<ul data-role="listview" <%=data_theme%> >
		<% @contests.each do |contest| %>
		<li class="mypadding">
		In <%= contest.team.sport.description%> <br>
		<%= contest.team.city %> vs <%= contest.name %> <br>
		<%= if contest.end > DateTime.now then
			link_to contest.end.strftime("%B %d, %Y"), contest_branches_path(contest) else
			'Closed' end %>
		</li>
		<% end %>
	</ul>

app/views/contests/new.html.erb
<h1>New contest </h1>

<%= render 'form' %>

<%= link_to 'Back', team_contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contest.name %>
</p>

<p>
  <b>First game:</b>
  <%= @contest.first_game %>
</p>

<p>
  <b>Last game:</b>
  <%= @contest.last_game %>
</p>

<p>
  <b>Start:</b>
  <%= @contest.start.to_s(:custom_date_time) %>
</p>

<p>
  <b>End:</b>
  <%= @contest.end.to_s(:custom_date_time) %>
</p>

<p>
  <b>Team:</b>
	<% if !@contest.team.nil?%>
  	<%= @contest.team.city %>
	<%end%>
</p>



<%= link_to 'Edit', edit_team_contest_path(@team, @contest) %> |
<%= link_to 'Back', team_contests_path %>

<br />