config/routes.rb
Fanbase::Application.routes.draw do
  
  

  resources :users
  resources :sessions, :only => [:new, :create, :destroy] # the ":only" and hash restricts the full set of CRUD to just those listed

  resources :sports do
    resources :teams
  end
  
  resources :sports do
    resources :types
  end
  
  resources :types do
    resources :events
  end
  

  resources :teams do
    resources :players
  end
  
  resources :teams do
    resources :contests
  end
      
  resources :contests do
    resources :branches
  end
  

  
  
  resources :users do
    resources :branches
  end
  

  
  root :to => 'pages#home'
  
  get "sessions/new"
  get "pages/home"
  
  match '/admin', :to => 'pages#admin'
  match '/signup', :to => 'users#new' 
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match 'contest/:team_id/team/:team_id/players', :to => 'team#players#index'

  

end

app/models/player.rb
class Player < ActiveRecord::Base
  
  attr_accessible :last_name, :first_name, :first_game, :last_game, :position, 
                  :team_id, :id, :branches_count
  
  # attr_accessor :last_first_name
  
  # validates :last_name, first_name, :presence => true
  
  belongs_to :team, :class_name => 'Team', :foreign_key => "team_id"
  has_many :branches
  
  # has_and_belongs_to_many :branches
  
  validates_each  :last_name,
                  :first_name,
                  :first_game,
                  :last_game,
                  :position,
                  do |record, attr, value|
                    if value.blank?
                      record.errors.add(attr, "cannot be blank.")
                    end
                  end
                  
    def player_name
        first_name + ' ' + last_name
      end
      
    def last_first_name
        last_name + ', ' + first_name
      end
      
            
    def branches_count
      branches.count
    end                  
    
    def show_branch_stats
      player_name + ' (' + branches_count.to_s() + ')'
    end
    

                  
  end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_filter :authenticate, :except => [:index, :show]
  before_filter :authenticate_admin, :except => [:index, :show]


  include PlayersHelper
  helper_method :sort_column, :sort_direction
  
  # GET /players
  # GET /players.json
  def index
    contest_if
    @team = Team.find(params[:team_id])
    if !@contest.nil? then
      # @players = @team.players.order(:branches_count).reverse
      @players = @team.players.sort_by{|p| p.branches.count }.reverse
    else
      @players = @team.players.order(sort_column + " " + sort_direction)
    end

    respond_to do |format|
      format.html #index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])
 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @team = Team.find(params[:team_id])    
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @team = Team.find(params[:team_id])
    @player = @team.players.build(params[:player_id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to [@team, @player], notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to [@team, @player], notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to team_players_url }
      format.json { head :no_content }
    end
  end
  

  private
  
  def sort_column
    params[:sort] || "last_name"
  end
  
  def sort_direction
    params[:direction] || "asc"
  end
  
  
  
  
  
  
  
  
  
end

app/helpers/players_helper.rb
module PlayersHelper
  
  def contest_if
    if params[:contest_id] then @contest = Contest.find(params[:contest_id]) end
  end
  
  def branch_count_this_contest(player_id, contest_id)
    branches = Branch.find(:all,
                        :conditions => ['player_id =? and contest_id =?',
                        player_id, contest_id])
    branches.count
  end
  
  def players_this_contest
  @players = Player.find(:all, 
                   :conditions => ["team_id = ?", :team_id], 
                   :order => :last_name)
  end
  
  
  
end

app/views/players/_form.html.erb
<%= form_for([@team, @player]) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :first_game %><br />
    <%= f.number_field :first_game %>
  </div>
  <div class="field">
    <%= f.label :last_game %><br />
    <%= f.number_field :last_game %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/_picks.html.erb
<h1>Listing picks for <%=@contest.name%> </h1>

<table>
  <tr>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.player_name %></td>
    <td><%= branch_count_this_contest(player.id, @contest.id)%></td>
  </tr>
<% end %>
</table>

<%= link_to 'Back', contest_branches_path(@contest)%>

app/views/players/_players.html.erb
<h1>Listing players</h1>

<table class="pretty">
  <tr>
    <th>id</th>
    <th><%= sortable "last_name", "Last Name" %></th>
    <th><%= sortable "first_name", "First Name" %></th>
    <th><%= sortable "first_game", "First Game" %></th>
    <th><%= sortable "last_game", "Last Game" %></th>
    <th><%= sortable "position", "Position" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
	<td><%= player.id %></td>
    <td><%= player.last_name %></td>
    <td><%= player.first_name %></td>
    <td><%= player.first_game %></td>
    <td><%= player.last_game %></td>
    <td><%= player.position %></td>
    <td><%= link_to 'Show', team_player_path(@team, player) %></td>
    <td><%= link_to 'Edit', edit_team_player_path(@team, player) %></td>
    <td><%= link_to 'Destroy', team_player_path(@team, player), confirm: 'Are you sure?', 
																method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back to All Teams ', sport_teams_path(@team.sport_id)%> |
<%= link_to 'New Player', new_team_player_path %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', team_player_path %> |
<%= link_to 'Back', team_players_path %>

app/views/players/index.html.erb
<%if admin?%>
	
	<%= render 'players'%>
	
	<%else%>

	<%= render 'picks'%>

<%end%>

app/views/players/index.mobile.erb
<h3>Listing picks for <%=@contest.name%> </h3>
	<ul data-role="listview" <%=data_theme%>>

	<% @players.each do |player| %>
	<li>
    <%= player.player_name %> 
	<span class="ui-li-count"><%= branch_count_this_contest(player.id, @contest.id)%> </span>
	</li>
	<% end %>
</ul>

<div class="mypadding">
	</br>
<%= link_to 'Back', contest_branches_path(@contest)%>
</div>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', team_players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Last name:</b>
  <%= @player.last_name %>
</p>

<p>
  <b>First name:</b>
  <%= @player.first_name %>
</p>

<p>
  <b>First game:</b>
  <%= @player.first_game %>
</p>

<p>
  <b>Last game:</b>
  <%= @player.last_game %>
</p>

<p>
  <b>Position:</b>
  <%= @player.position %>
</p>


<%= link_to 'Edit', edit_team_player_path(@team, @player) %> |
<%= link_to 'Back', team_players_path %>