config/routes.rb
Fanbase::Application.routes.draw do
  
  

  resources :users
  resources :sessions, :only => [:new, :create, :destroy] # the ":only" and hash restricts the full set of CRUD to just those listed

  resources :sports do
    resources :teams
  end
  
  resources :sports do
    resources :types
  end
  
  resources :types do
    resources :events
  end
  

  resources :teams do
    resources :players
  end
  
  resources :teams do
    resources :contests
  end
      
  resources :contests do
    resources :branches
  end
  

  
  
  resources :users do
    resources :branches
  end
  

  
  root :to => 'pages#home'
  
  get "sessions/new"
  get "pages/home"
  
  match '/admin', :to => 'pages#admin'
  match '/signup', :to => 'users#new' 
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match 'contest/:team_id/team/:team_id/players', :to => 'team#players#index'

  

end

app/views/layouts/_footer.mobile.erb
<!-- <div data-role="footer" <%=data_theme%> -->
	<br/>
	<br/>
	<div data-role="button" data-mini="true" <%=data_theme%> class="footer">
	<div id="center_logo">
		<%= link_to sponsor_logo, "http://www.trendingbuffalo.com" %>
	</div>
	</div>
<!-- </div><!-- /footer -->

app/views/layouts/_header.html.erb
<header>
	<div class="sponsor round">
	<%= link_to sponsor_logo, root_path, :class => "round" %>
	</div>
	<nav class="round">
		<ul>
			<% if signed_in? %>
			<li><%= link_to "Home", contests_path %></li> 
			<li><%= link_to "Profile", user_path(current_user) %></li> 
			<%end%>
			<% if signed_in? %>
				<% if admin? %>
				<li><%= link_to "Admin", admin_path %></li>
				<li><%= link_to "Users", users_path %></li> 
				<li><%= link_to "Settings", edit_user_path(current_user) %></li> 
				<%end%>
			<li><%= link_to "Sign out", signout_path, :confirm => "You sure?"%></li>
			<% else %>
			<li><%= link_to "Sign in", signin_path %></li>
		</ul>
		<%end%>
	</nav>	
</header>

app/views/layouts/_header.mobile.erb
<div data-role="header" <%= data_theme %> >
	<% if signed_in? %>
	<h1><%= link_to 'Game-Sim', contests_path%></h1>
	<%= link_to "Sign Out", signout_path, "class" => "ui-btn-left", "data-mini" => "true", 
		:confirm => "You sure?" %>
	<% else %>
	<h1><%= link_to 'Game-Sim', root_path%></h1>
	<%= button_to "Sign in", signin_path, "class" => "ui-btn-left", "data-mini" => "true"%>
	<%end%>	
</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %> 
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!-- [if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]  -->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/_stylesheets.mobile.erb
<%=stylesheet_link_tag "jquery.mobile.min.css", "mobile.css"%>
<%=javascript_include_tag "application.js"%>
<%= javascript_include_tag "jquery.js" %>
<%=javascript_include_tag "jquery.mobile.min.js"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
  		<%= csrf_meta_tags %>
		<%= render 'layouts/stylesheets' %>
  		<%= javascript_include_tag "application" %>
	</head>
		<% if signed_in? && admin? %>
		<body class="admin">
		<div class="bigcontainer">
		<%else%>
		<body>
		<div class="container">
		<%end%>
      	<%= render 'layouts/header' %>
			<section class="round">
			<% flash.each do |key, value | %>
				<div class ="flash <%= key %>" ><%= value %> </div> 
			<% end %>
			<%= yield %>
			</section>

		</div>
		
	</body>

</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<meta name ="viewport" content="width=device-width, initial-scale=1">
  		<%= csrf_meta_tags %>
		<%= render 'layouts/stylesheets' %>
	</head>
		<body>
		<div class="wrapper">
			<div date-role="page" <%= data_theme %>>
	      	<%= render 'layouts/header' %>
				<div data-role="content" <%= data_theme %> >
					<%= yield %>
					<br/>
					<br/>
					<br/>				
					<div id="center_logo">__________</div>
				</div>
			</div>
			<div class="footer">
			<%= render 'layouts/footer' %>
			</div>
		</div>
	</body>
</html>